### ISSUE TITLE
Not redirecting on click of `prerender` button

### ISSUE THREAD

**Issue by ishwarrimal** [GoogleChromeLabs/instant-seamless-demo#6]
**What is happening?**
On click of prerender, only a <script> tag is added to the body with the following object:
```
<script>
{
                "prerender":[
                  {
                    "source": "list",
                    "urls": ["http://localhost:3000/vegetables/carrots"]
                  }
                ]
 }
</script>
```
There is no redirection.

**Expected behaviour**
Should pre fetch the resource and redirect to the new page.

**Steps Followed**
- Cloned the repo
- Checked out the main branch -> same issue.
- Checked out to the `codelab` branch and followed instructions from this [doc](https://codelabs.developers.google.com/create-an-instant-and-seamless-web-app#2) -> same issue.
- Checked out to the `codelab-complete` branch -> same issue

**Comment by ishwarrimal** [comment]
Also, I am new to Next, and the thing that's happening on click of `prerender` makes no sense to me. It's just adding an object inside a script.
I don't see any logic in the codebase which makes use of this object-> URL and fetches the resource.

**Comment by sisidovski** [comment]
Hi @ishwarrimal,

Thank you for opening the issue, and sorry for the late response.

> On click of prerender, only a <script> tag is added to the body with the following object:

That is intended behavior. The prerender button on this demo performs prerendering but doesn't do redirections. When the button adds a `speculationrules` script tag to the page, the browser fetches the page written in the tag and starts prerendering on the background. Developers don't have to write any specific logic to fetch the page manually.

Please take a look at web.dev doc for more details.
https://web.dev/speculative-prerendering/#same-origin-prerendering-trial
